---
abstract: "Support module for the 'pegex' CLI command"
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Pegex-Cmd
requires:
  Pegex: '0.25'
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/pegex-cmd-pm/issues
  homepage: https://github.com/ingydotnet/pegex-cmd-pm
  repository: https://github.com/ingydotnet/pegex-cmd-pm.git
version: '0.14'
